# Désactivé temporairement - utiliser simple-ci.yml
# Ce fichier est désactivé pour éviter les erreurs
# Utilisez simple-ci.yml à la place

# Le workflow complexe est désactivé car il causait des erreurs
# Utilisez le workflow simple-ci.yml qui fonctionne correctement

# Pour réactiver ce workflow plus tard :
# 1. Décommentez les sections name, on, jobs
# 2. Testez étape par étape
# 3. Vérifiez que toutes les dépendances sont installées